CREATE TABLE armaments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    craft_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (craft_id) REFERENCES space_crafts(id) ON DELETE CASCADE
);
